name: Trenton Frey
title: Trenton Frey | ePortfolio
description: Trenton Frey | ePortfolio
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
 
email: trenton.frey@snhu.edu
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
